/*using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using PressureMonitor.Models;*/


//This was the original design for the RealTimeAlertController which would insert alerts into the Alerts table based on the most recent PressureFrame data.
//This did not work as intended so the other approach in PatientController.cs was trialed instead.
//Left in for proof of contribution
/*namespace PressureMonitor.Controllers
{
   public class ErrorController : Controller
   {
       public IActionResult Index()
       {
           //  Create empty model
           var model = new RealTimeAlertModel();


           // Connection string to your SQLite DB
           var connectionString = "Data Source=PressureMonitor.db";


           using (var connection = new SqliteConnection(connectionString))
           {
               connection.Open();


               //  SQL command to get most recent row in the PressureFrames table
               var command = connection.CreateCommand();
               command.CommandText =
                   @"
                   SELECT
                       ContactAreaPercentage,
                       PeakPressure,
                       MinValue,
                       Id
                   FROM pressureFrames
                   ORDER BY Timestamp DESC
                   LIMIT 1;
               ";


               using (var reader = command.ExecuteReader())
               {
                   if (reader.Read())
                   {
                       model.ContactArea.ContactAreaPercentage = reader.GetInt32(0);
                       model.PeakPressure.PeakPressure = reader.GetInt32(1);
                       model.MinimumPressure.MinValue = reader.GetInt32(2);
                       var frameId = reader.GetInt32(3);
                     
                       //INSERT INTO Alerts TABLE
                       var insertCmd = connection.CreateCommand();
                       insertCmd.CommandText =
                           @"
       INSERT INTO Alerts
       (FrameId, SeverityLevel, TimeOfAlert, Status, Message, AutoGenerated)
       VALUES
       ($frameId, $severity, $time, $status, $message, $auto);
   ";
                                            
                       //Placeholder values for alert insertion. These would be determined based on evaluation logic.
                       insertCmd.Parameters.AddWithValue("$frameId", 1);
                       insertCmd.Parameters.AddWithValue("$severity", "High");
                       insertCmd.Parameters.AddWithValue("$time", DateTime.Now);
                       insertCmd.Parameters.AddWithValue("$status", "Active");
                       insertCmd.Parameters.AddWithValue("$message", "Peak Pressure Exceeded");
                       insertCmd.Parameters.AddWithValue("$auto", 1);


                       insertCmd.ExecuteNonQuery();
                   }


               }
           }
           return View(model);
       }
   }
}*/
