// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressureMonitor.Models;

#nullable disable

namespace PressureMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206155519_AddClinicianPatients")]
    partial class AddClinicianPatients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PressureMonitor.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PressureMonitor.Models.Clinician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clinicians");
                });

            modelBuilder.Entity("PressureMonitor.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClinicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PressureMonitor.Models.PressureFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AveragePressure")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ContactAreaPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeakPressure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PressureMapId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PressureMapId");

                    b.ToTable("PressureFrames");
                });

            modelBuilder.Entity("PressureMonitor.Models.PressureMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PressureMaps");
                });

            modelBuilder.Entity("PressureMonitor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PressureMonitor.Models.Admin", b =>
                {
                    b.HasOne("PressureMonitor.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("PressureMonitor.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PressureMonitor.Models.Clinician", b =>
                {
                    b.HasOne("PressureMonitor.Models.User", "User")
                        .WithOne("Clinician")
                        .HasForeignKey("PressureMonitor.Models.Clinician", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PressureMonitor.Models.Patient", b =>
                {
                    b.HasOne("PressureMonitor.Models.Clinician", "Clinician")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PressureMonitor.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("PressureMonitor.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PressureMonitor.Models.PressureFrame", b =>
                {
                    b.HasOne("PressureMonitor.Models.PressureMap", "PressureMap")
                        .WithMany("Frames")
                        .HasForeignKey("PressureMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PressureMap");
                });

            modelBuilder.Entity("PressureMonitor.Models.PressureMap", b =>
                {
                    b.HasOne("PressureMonitor.Models.Patient", "Patient")
                        .WithMany("PressureMaps")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PressureMonitor.Models.Clinician", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PressureMonitor.Models.Patient", b =>
                {
                    b.Navigation("PressureMaps");
                });

            modelBuilder.Entity("PressureMonitor.Models.PressureMap", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("PressureMonitor.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
